PhotoAlbum/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PhotoAlbum.Business.Interfaces;
using System.IO;
using PhotoAlbum.Business.DTO;
using PhotoAlbum.Models;

namespace PhotoAlbum.Controllers
{
    [Authorize]
    public class PhotoController : Controller
    {
        private readonly IPhotoService photoService;
        private readonly ITagService tagService;

        public PhotoController(IPhotoService photos, ITagService tags)
        {
            photoService = photos;
            tagService = tags;
        }

        public ActionResult ShowPhoto(int id)
        {
            string login = User.Identity.Name;
            var photo = photoService.GetPhotoById(id, login);

            return View(photo);
        }

        public ActionResult ShowPhotos(string albumName, int page = 1)
        {
            TempData["AlbumName"] = albumName;
            
            return View();
        }

        public ActionResult GetPhotosOfAlbum(string userName, string albumName, int page = 1)
        {
            TempData["AlbumName"] = albumName;

            if(userName == null)
                userName = User.Identity.Name;

            string login = User.Identity.Name;
            var photos = new PageData<PhotoPropertiesDTO>(photoService.GetPhotosPropertiesOfAlbum(userName, albumName, login), page);
            return PartialView(photos);
        }

        public ActionResult ShowPhotoByTag(string tagName, int page=1)
        {
            TempData["TagName"] = tagName;
            
            return View();
        }
        
        public ActionResult GetPhotosByTag(string tagName, int page = 1)
        {
            TempData["TagName"] = tagName;

            string login = User.Identity.Name;
            var photos = tagService.GetPhotosByTag(tagName, login);
            var photoPage = new PageData<PhotoPropertiesDTO>(photos, page);

            return PartialView(photoPage);
        }


        [HttpPost]
        public ActionResult SetRating(int idPhoto, int rating)
        {
            string login = User.Identity.Name;
            photoService.SetRaiting(idPhoto, login, rating);

            return RedirectToAction("ShowPhoto", new { id = idPhoto });
        }


        public ActionResult EditRating(int idPhoto, int rating)
        {
            string login = User.Identity.Name;
            var ratingView = new RatingViewModel
            {
                Rating = photoService.SetRaiting(idPhoto, login, rating),
                NewRating = rating,
                IdPhoto = idPhoto
            };

            return PartialView(ratingView);
        }

        private IEnumerable<byte[]> ConvertToArrayBytes(HttpPostedFileBase[] images)
        {
            foreach (var image in images)
            {
                BinaryReader reader = new BinaryReader(image.InputStream);
                byte[] imageBytes = reader.ReadBytes((int)image.ContentLength);

                yield return imageBytes;
            }
        }

        [HttpPost]
        public ActionResult Upload(string albumName, HttpPostedFileBase[] files)
        {
            string login = User.Identity.Name;
            photoService.CreateNewPhoto(ConvertToArrayBytes(files), albumName, login);

            return RedirectToAction("EditAlbum", "Album", new { albumName = albumName });
        }

        public ActionResult Delete(string albumName, int idPhoto)
        {
            string login = User.Identity.Name;
            photoService.DeletePhoto(login, albumName, idPhoto);

            return RedirectToAction("EditAlbum", "Album", new { albumName = albumName });
        }

        public ActionResult EditPhoto(string albumName, int idPhoto)
        {
            ViewBag.Id = idPhoto;
            var tags = tagService.GetPhotoTegName(idPhoto);

            return View(tags);
        }

        [HttpPost]
        public ActionResult TagAdd(int idPhoto, string nameTag)
        {
            tagService.AddTagToPhoto(idPhoto, nameTag);
            var tags = tagService.GetPhotoTegName(idPhoto);

            return PartialView(tags);
        }
    }
}

PhotoAlbum/Views/Photo/EditPhoto.cshtml
@model IEnumerable<string>

@{
    ViewBag.Title = "Добавленеие тегов";
}

<div>
    @using (Ajax.BeginForm("TagAdd","Photo", new { idPhoto = @ViewBag.Id }, new AjaxOptions { UpdateTargetId = "results", LoadingElementId = "loading"}))
    {
        <label>Имя тега</label>
        <input type="text" name="nameTag" />
        <input type="submit" class="btn btn-dark" value="Добавить" />
    }
    <div id="loading" style="display:none; text-align:center">
        <img src="~/Content/loader_orange.gif" width="48px">
    </div>
    <div id="results">
            <h3>Все теги фотографии:</h3>
            <ul>
                @foreach (var item in Model)
                {
                    <li>@item</li>
                }
            </ul>
    </div>
</div>

PhotoAlbum/Views/Photo/EditRating.cshtml
@model PhotoAlbum.Models.RatingViewModel
                        
Rating: @Model.RatingString

@if (!@Model.IsMY)
{
    using (Ajax.BeginForm("EditRating", "Photo", new { idPhoto = Model.IdPhoto }, new AjaxOptions { UpdateTargetId = ("Rating-"+ @Model.IdPhoto), LoadingElementId = "loading" }))
    {
        @Html.ButtonsRatingSelected(@Model.NewRating);
    }

    <div id="loading" style="display:none; text-align:center">
        <img src="~/Content/loader_orange.gif" width="20px">
    </div>
}

PhotoAlbum/Views/Photo/GetPhotosByTag.cshtml
@model PhotoAlbum.Models.PageData<PhotoAlbum.Business.DTO.PhotoPropertiesDTO>

@{
    int count = Model.Content.Count();
}
<style>
    img {
        max-height: 200px;
        max-width: 429px;
        min-height: 160px;
        min-width: 100px;
        float: none;
        margin: 0 0 40px 0;
    }

    a {
        text-decoration: none;
    }
</style>
<div class="container changeimg">
    @{
        int i = 0, ind = 0;

        int[] nex = new int[count];
        foreach (var p in Model.Content)
        {
            nex[ind++] = p.Id;
        }

        ind = 1;

        foreach (var photo in Model.Content)
        {
            <div class="card" style="background-color:#F87085">
                <div class="card-image" id="img-@photo.Id">
                    @Html.Raw("<img src=\"data:image/jpeg;base64,"
                        + Convert.ToBase64String(photo.Image) + "\" />")
                    <span class="card-title">
                        Теги:
                        @foreach (var tagName in photo.TagName)
                        {
                            <a href="@Url.Action("ShowPhotoByTag", "Photo", new { tagName = @tagName })" class="chip">@tagName</a>
                        }
                    </span>
                </div>
                <div class="card-content">

                    <div id="propertis" style="padding:14px; display:block;">
                        <div style="display:block;">
                            <div id="Rating-@photo.Id">
                                Рейтинг: @photo.Rating

                                @if (!photo.IsMy)
                                {
                                    using (Ajax.BeginForm("EditRating", "Photo", new { idPhoto = @photo.Id }, new AjaxOptions { UpdateTargetId = ("Rating-" + @photo.Id), LoadingElementId = "loading" }))
                                    {
                                        @Html.ButtonsRatingSelected(photo.MyRating);
                                    }

                                    @*<div id="loading" style="display:none; text-align:center">
                                            <img src="~/Content/loader_orange.gif" width="20px">
                                        </div>*@
                                }
                            </div>
                        </div>
                        @*<div class="card-action">
                                    Теги:
                                    @foreach (var tagName in photo.TagName)
                                    {
                                        <a href="@Url.Action("ShowPhotoByTag", "Photo", new { tagName = @tagName })" class="badge">@tagName</a>
                                    }
                            </div>*@
                    </div>
                </div>
            </div>
            i = photo.Id;
        }
    }

    <div id="allPhotos">
        @foreach (var item in Model.Content)
        {
            <a href="#img-@item.Id">
                @Html.Raw("<img src=\"data:image/jpeg;base64,"
                                + Convert.ToBase64String(item.Image) + "\" />")
            </a>
        }

        <br />
        <div>
            @if (Model.CountPage > 1)
            {
                @Html.PageLinks(Model.NumberPage, Model.CountPage, x => Url.Action("ShowPhotoByTag", "Photo", new { tagName = TempData["TagName"], page = x }))
            }
        </div>
    </div>
</div>

PhotoAlbum/Views/Photo/GetPhotosOfAlbum.cshtml
@model PhotoAlbum.Models.PageData<PhotoAlbum.Business.DTO.PhotoPropertiesDTO>

@{
    int count = Model.Content.Count();
}
<style>
    img {
        max-height: 200px;
        max-width: 429px;
        min-height: 160px;
        min-width: 100px;
        float: none;
    }

    a {
        text-decoration: none;
    }
</style>
<div class="container changeimg">
    @{
        int i = 0, ind = 0;

        int[] nex = new int[count];
        foreach (var p in Model.Content)
        {
            nex[ind++] = p.Id;
        }

        ind = 1;

        foreach (var photo in Model.Content)
        {
            <div class="card" style="background-color:#F87085">
                <div class="card-image" id="img-@photo.Id">
                    @Html.Raw("<img src=\"data:image/jpeg;base64,"
                        + Convert.ToBase64String(photo.Image) + "\" />")
                    <span class="card-title">
                        Теги:
                        @foreach (var tagName in photo.TagName)
                        {
                            <a href="@Url.Action("ShowPhotoByTag", "Photo", new { tagName = @tagName })" class="badge">@tagName</a>
                        }
                    </span>
                </div>
                <div class="card-content">
                    <div id="propertis" style="padding:14px; display:block;">
                        <div style=" display:block;">
                            <div id="Rating-@photo.Id">
                                Рейтинг: @photo.Rating

                                @if (!photo.IsMy)
                                {
                                    using (Ajax.BeginForm("EditRating", "Photo", new { idPhoto = @photo.Id }, new AjaxOptions { UpdateTargetId = ("Rating-" + @photo.Id), LoadingElementId = "loading" }))
                                    {
                                        @Html.ButtonsRatingSelected(photo.MyRating);
                                    }

                                    @*<div id="loading" style="display:none; text-align:center">
                                            <img src="~/Content/loader_orange.gif" width="20px">
                                        </div>*@
                                }
                            </div>
                        </div>

                    </div>
                </div>
                @*<div class="card-action">
                            Теги:
                            @foreach (var tagName in photo.TagName)
                            {
                                <a href="@Url.Action("ShowPhotoByTag", "Photo", new { tagName = @tagName })" class="badge">@tagName</a>
                            }
                    </div>*@
            </div>
            i = photo.Id;
        }
    }

    <div id="allPhotos">
        @foreach (var item in Model.Content)
        {
            <a href="#img-@item.Id">
                @Html.Raw("<img src=\"data:image/jpeg;base64,"
                                    + Convert.ToBase64String(item.Image) + "\" />")
            </a>
        }

        <br />
        <div>
            @if (Model.CountPage > 1)
            {
                @Html.PageLinks(Model.NumberPage, Model.CountPage, x => Url.Action("ShowPhotos", "Photo", new { albumName = TempData["AlbumName"], page = x }))
            }
        </div>
    </div>
</div>

PhotoAlbum/Views/Photo/ShowPhoto.cshtml
@model PhotoAlbum.Business.DTO.PhotoPropertiesDTO

@{
    ViewBag.Title = "ShowPhoto";
}

<style>
    /*img{
        max-width:600px;
        max-height:500px;
        display:block; 
        margin:0 auto;
    }

    button {
        background-color: orange;
        border: 1px solid #7a7b7e;
        width: 28px;
        height: 28px;
        border-radius: 30px;
   }

    .selected{
        background-color: red;
    }

    .badge {
        display: inline-block;
        min-width: 10px;
        padding: 3px 7px;
        font-size: 12px;
        font-weight: 700;
        line-height: 1;
        color: #fff;
        text-align: center;
        white-space: nowrap;
        vertical-align: baseline;
        background-color: #E39821;
        border-radius: 10px;
    }*/
</style>

<h2>ShowPhoto</h2>

<div>
    <hr />
    @Html.Raw("<img src=\"data:image/jpeg;base64,"
                                + Convert.ToBase64String(Model.Image) + "\" />")
    <div id="propertis" style="padding:14px;">
        <div style="float:left;">
            Рейтинг: @Model.Rating

            @if (!Model.IsMy)
            {
                using (Html.BeginForm("SetRating", "Photo", new { idPhoto = @Model.Id }, FormMethod.Post))
                {
                    @Html.ButtonsRatingSelected(Model.MyRating);
                }
            }
        </div>
        <div style="float:right;">
            @foreach (var tagName in Model.TagName)
            {
                <a href="@Url.Action("ShowPhotoByTag", "Photo", new { tagName = @tagName })" class="badge">@tagName</a>
            }
        </div>
    </div>
</div>

PhotoAlbum/Views/Photo/ShowPhotoByTag.cshtml
@{
    ViewBag.Title = "Фотографии";
}

<style>
   a > img{
        max-height: 200px;
        max-width: 260px;
        min-height: 160px;
        min-width: 100px;
        float: none;
        margin: 0 0 40px 0;
    }
</style>

<h2>Search by tag @TempData["TagName"]</h2>

<hr />

<div id="gallery">
    @{Html.RenderAction("GetPhotosByTag", new { tagName = @TempData["TagName"] });}
</div>

PhotoAlbum/Views/Photo/ShowPhotos.cshtml
@{
    ViewBag.Title = "Фотографии";
}

<style>
   a > img{
        max-height: 200px;
        max-width: 260px;
        min-height: 160px;
        min-width: 100px;
        float: none;
        margin: 0 0 40px 0;
    }
   a{
       text-decoration: none;
   }
</style>

<h2>@TempData["AlbumName"]</h2>
<hr />

<div id="gallery">
    @{Html.RenderAction("GetPhotosOfAlbum", new { albumName = @TempData["AlbumName"] });}
</div>

PhotoAlbum/Views/Photo/TagAdd.cshtml
@model IEnumerable<string>

<div>
    <h3>Все тиги фотографии:</h3>
    <ul>
        @foreach (var item in Model)
        {
            <li>@item</li>
        }
    </ul>
</div>

PhotoAlbum/Views/Photo/Upload.cshtml
@{
    ViewBag.Title = "Загрузка фотографий";
}

<h2>Загрузка фотографий</h2>

<form action="/photo/upload" enctype="multipart/form-data" method="post">
    <label>Загрузка картинок:</label>
    <input accept="image/*" id="File1" multiple="multiple" name="File1" type="file" />
    <input id="btnUpload" type="submit" value="Отправить" />
</form>